# server (eureka 默认端口为：8761)
server:
  port: 8761

# spring
spring:
  application:
    name: erueka

# eureka
eureka:
  client:
    # 是否注册到eureka
    register-with-eureka: false
    # 是否从eureka获取注册信息
    fetch-registry: false
    availability-zones:
      honghu: honghuZone
    service-url:
      honghuZone: http://honghu:123456@localhost:8761/eureka/
      defaultZone: http://honghu:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    metadataMap:
      zone: honghuZone
      user: ${security.user.name}
      password: {security.user.password}

  # 指定环境
  environment: dev
  #指定数据中心
  datacenter: honghu
  # 关闭自我保护模式
  server:
    enable-self-preservation: false
    #设置清理无效节点的时间间隔，默认60000，即是60s
    eviction-interval-timer-in-ms: 60000

# 服务认证
security:
  basic:
    enabled: false
  user:
    name: honghu
    password: 123456

management:
  security:
    enabled: false